before:
  hooks:
    - go mod download
builds:
  - id: azswitch
    main: .
    binary: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
    goarm: [6, 7]