before:
  hooks:
    - go mod download
builds:
  - id: azswitch
    main: .
    binary: azswitch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
archives:
  - id: azswitch
    builds:
      - azswitch
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
scoop:
  url_template: "https://github.com/eliasericsson/azswitch/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: eliasericsson
    name: azswitch
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  description: "Switch Azure subscriptions faster."
  license: GPL2
