name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: windowsrelease
          path: azswitch_windows_amd64/azswitch.exe

  chocolatey:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Strip version
        shell: powershell
        run: |
          '${{ github.event.release.tag_name }}' -replace '[A-Za-z]' | Out-File -FilePath $env:TAG -Encoding utf8 -Append

      - name: Print tag
        shell: powershell
        run: echo ${{ env.TAG }}

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "__VERSION__"
          replace: ${{ env.TAG }}

      - uses: actions/download-artifact@v2
        with:
          name: windowsrelease
          path: tools

      - name: Choco API
        uses: crazy-max/ghaction-chocolatey
        with:
          args: apikey --key ${{ secrets.CHOCOLATEY_API }} --source https://push.chocolatey.org/

      - name: Choco push
        uses: crazy-max/ghaction-chocolatey
        with:
          args: push azswitch.nupkg --source https://push.chocolatey.org/